---

version: "3"

services:

    app:
        image: myapp
        environment:
            BASE_DOMAIN: ${BASE_DOMAIN}
        expose:
            - "8000"
        labels:
              traefik.frontend.rule: Host:app.${BASE_DOMAIN}

    cdn:
        image: mycdn
        labels:
              traefik.frontend.rule: Host:cdn.${BASE_DOMAIN}
